### ISSUE TITLE
Problem with custom user model.

### ISSUE THREAD

**Issue by saileshkush95** [RamezIssac/django-tabular-permissions#12]
![DeepinScreenshot_select-area_20191231204451](https://user-images.githubusercontent.com/28560875/71625237-d3097c80-2c0e-11ea-95a1-12fefb00cdde.png)

Here is my custom user models

![DeepinScreenshot_select-area_20191231204646](https://user-images.githubusercontent.com/28560875/71625255-e4eb1f80-2c0e-11ea-9d1e-068fc129f130.png)

**Comment by RamezIssac** [comment]
Hello @saileshkush95 

I can see where the problem is.
Check this from the README, this should solve your issue.


> By default, just by including tabular_permissions in your installed_apps, the django.contrib.admin.UserAdmin (and GroupAdmin) are "patched" to include the tabular_permissions widget. If you have a custom UserAdmin, then set this option to False and make sure you either:

> Inherit from tabular_permissions.admin.TabularPermissionsUserAdmin and tabular_permissions.admin.TabularPermissionsGroupAdmin for User & Group ModelAdmin.
Or for a more direct and compact way, inherit your ModelAdmin from tabular_permissions.admin.UserTabularPermissionsMixin and tabular_permissions.admin.GroupTabularPermissionsMixin (comes before admin.ModelAdmin in the mro),
Set the user_permissions widget to tabular_permissions.widgets.TabularPermissionsWidget and remember to send a 3rd argument 'permissions' for Group Model Admin. See tabular_permissions.admin for information.

**Comment by saileshkush95** [comment]
Thanks
